IS_API_KEY = ""
IS_API_ENDPOINT = "https://is.orienteering.sk/api"
SANDBERG_API_ENDPOINT = "https://senzor.robotika.sk/sks/api.php/api"
GOOGLE_CREDENTIALS_PATH = ""
GOOGLE_EMAILS = "gabko.kozuch@gmail.com"
CLUB_ID = 46
HOME_DIR = ""
