# API configuration
# is.orienteering.sk API
api_key = ''
api_endpoint = 'https://is.orienteering.sk/api'

# Sandberg API
api_key = ''
api_endpoint = ''

# google calendar API
credentials_path = ''
emails = []

# club info
club_id = 81

# home dir
path = ''
